name: "Clone Github Releases"
description: "Clone the releases in one repo to this one"
author: "Andrew Herrington"
inputs:
  token:
    description: "Github token"
    required: true
  repo:
    description: "Source repo to clone from"
    required: true
  target:
    description: "Target for new tags/releases in this repo"
    default: ""
  skip_draft:
    description: "Skip draft releases"
    default: False
  skip_prerelease:
    description: "Skip Prereleases"
    default: False
  limit:
    description: "A limit of how many releases to add on a single run. Good for not overwhelming CI systems"
    default: 0
  dry_run:
    description: "If true, just output what releases would have been made but do not make releases"
    default: False
  min_version:
    description: "If set, we will ignore any releases from the source repo that are less than min_version"
    default: ""
outputs:
  addedReleases:
    description: "Comma separated list of all the releases created"
  addedReleasesCount:
    description: "Count of releases added"
  skippedReleasesCount:
    description: "Count of releases skipped"
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icon: 'copy'
  color: 'blue'
