name: "Clone Github Releases"
description: "Clone the releases in one repo to this one"
author: "Andrew Herrington"
inputs:
  token:
    description: "Github token"
    required: true
  repo:
    description: "Soiurce repo to clone from"
    required: true
  target:
    description: "Target for new tags/releases in this repo"
    default: ""
  skip_draft:
    description: "Skip draft releases"
    default: False
  skip_prerelease:
    description: "Skip Prereleases"
    default: False
  limit:
    description: "A limit of how many releases to add on a single run. Good for not overwhelming CI systems"
    default: 0
  dry_run:
    description: "If true, we'll just output what releases we would have made but not actually make releases"
    default: False
outputs:
  addedReleases:
    description: "Comma separated list of all the releases created"
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icon: 'copy'
  color: 'blue'
