name: "Clone Releases"
description: "Clone the releases in one repo to this one"
author: "Andrew Herrington"
inputs:
  token:
    description: "Github token"
  repo:
    description: "Soiurce repo to clone from"
  target:
    description: "Target for new tags/releases in this repo"
    default: ""
outputs:
  addedReleases:
    description: "Comma separated list of all the releases created"
runs:
  using: "docker"
  image: "Dockerfile"
