name: Generate Docs
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  docs:
    name: Generate Docs
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: actions/checkout@v3
      - name: Run doc generation
        uses: npalm/action-docs-action
