name: Integration Test
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  integration-testing:
    name: Integration Testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        # https://github.com/stefanzweifel/git-auto-commit-action#commits-made-by-this-action-do-not-trigger-new-workflow-runs
        with:
          token: ${{ secrets.THIS_PAT }}
      - name: Test action
        id: test-action
        # test with the local checkout of the action
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repo: andrewthetechie/gha-clone-releases
      - name: Check outputs
        run: |
          test "${{ steps.test-action.outputs.addedReleases }}" == ""
