name: Integration Test
on: [push, pull_request]
jobs:
  integration-testing:
    name: Integration Testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout
      - name: Test action
        id: test-action
        uses: andrewthetechie/gha-clone-releases@${{ env.ref_name }}
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repo: andrewthetechie/gha-clone-releases
      - name: Check outputs
        run: |
          test "${{ steps.selftest.outputs.addedReleases }}" == ""
