name: Lint
on: [push, pull_request]
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.9
        uses: actions/setup-python@v4.0.0
        with:
          python-version: "3.9.2"
      - uses: actions/checkout@v3
        # https://github.com/stefanzweifel/git-auto-commit-action#commits-made-by-this-action-do-not-trigger-new-workflow-runs
        with:
          token: ${{ secrets.THIS_PAT }}
      - name: Run Pre-commit
        uses: pre-commit/action@v3.0.0
